In [1]:
import numpy as np
key_ids=np.array([1,2,1])
(key_ids == key_ids[0]).all()

False

In [23]:
a={}
len_candidates_list=0
for i in range(50):
    if i>40:
        a[i]=i-30
        len_candidates_list=len_candidates_list+i-30
    else:
        a[i]=1
        len_candidates_list=len_candidates_list+1        
    
    

    
self_prob = a.copy()#item出现频次的分布，是个dict
self_alias = self_prob.copy()
large_q = []
small_q = []

for i in self_prob:#i是key值，itemid等
    self_alias[i] = -1 #先全部变成-1
    self_prob[i] = self_prob[i] / len_candidates_list * len(self_prob)#相当于做了过缩放，使得出现一次的都在0-1的范围，出现2词以上有可能在0-1范围，也有可能>1
    if self_prob[i] > 1:#出现频次大的
        large_q.append(i)
    elif self_prob[i] < 1: #出现频次小的
        small_q.append(i)
#最终 self.alias中频率少的id对应的值为平频率大的id，代表选到这个id时，换成相应大频率id,并且越大的频率索引就越多的成为小频率索引得值，而对应大频率id值为-1,应该是选到这个id时，直接取。
while len(large_q) != 0 and len(small_q) != 0:#循环直到large_q或small_q有一个为空，这个过程除了small_q中的索引对应的self.alias变成1外，large_q中的部分相对频率小的索引也会在self.alias变成1
    l = large_q.pop(0)
    s = small_q.pop(0)
    self_alias[s] = l #alias中对应small_q中index的位置的值都变成large_q.pop(0)如类似形式 {23：32，24：-1...}
    self_prob[l] = self_prob[l] - (1 - self_prob[s])#进行此操作后出现频率大的索引概率会减少  0-1de 范围
    #所以每次循环只会large_q或者small_q其中一个少一个元素
    if self_prob[l] < 1:
        small_q.append(l)
    elif self_prob[l] > 1:
        large_q.append(l)

In [24]:
a

{0: 1,
 1: 1,
 2: 1,
 3: 1,
 4: 1,
 5: 1,
 6: 1,
 7: 1,
 8: 1,
 9: 1,
 10: 1,
 11: 1,
 12: 1,
 13: 1,
 14: 1,
 15: 1,
 16: 1,
 17: 1,
 18: 1,
 19: 1,
 20: 1,
 21: 1,
 22: 1,
 23: 1,
 24: 1,
 25: 1,
 26: 1,
 27: 1,
 28: 1,
 29: 1,
 30: 1,
 31: 1,
 32: 1,
 33: 1,
 34: 1,
 35: 1,
 36: 1,
 37: 1,
 38: 1,
 39: 1,
 40: 1,
 41: 11,
 42: 12,
 43: 13,
 44: 14,
 45: 15,
 46: 16,
 47: 17,
 48: 18,
 49: 19}

In [25]:
self_prob

{0: 0.2840909090909091,
 1: 0.2840909090909091,
 2: 0.2840909090909091,
 3: 0.2840909090909091,
 4: 0.2840909090909091,
 5: 0.2840909090909091,
 6: 0.2840909090909091,
 7: 0.2840909090909091,
 8: 0.2840909090909091,
 9: 0.2840909090909091,
 10: 0.2840909090909091,
 11: 0.2840909090909091,
 12: 0.2840909090909091,
 13: 0.2840909090909091,
 14: 0.2840909090909091,
 15: 0.2840909090909091,
 16: 0.2840909090909091,
 17: 0.2840909090909091,
 18: 0.2840909090909091,
 19: 0.2840909090909091,
 20: 0.2840909090909091,
 21: 0.2840909090909091,
 22: 0.2840909090909091,
 23: 0.2840909090909091,
 24: 0.2840909090909091,
 25: 0.2840909090909091,
 26: 0.2840909090909091,
 27: 0.2840909090909091,
 28: 0.2840909090909091,
 29: 0.2840909090909091,
 30: 0.2840909090909091,
 31: 0.2840909090909091,
 32: 0.2840909090909091,
 33: 0.2840909090909091,
 34: 0.2840909090909091,
 35: 0.2840909090909091,
 36: 0.2840909090909091,
 37: 0.2840909090909091,
 38: 0.2840909090909091,
 39: 0.2840909090909091,
 40: 0.284

In [27]:
self_alias

{0: 41,
 1: 42,
 2: 43,
 3: 44,
 4: 45,
 5: 46,
 6: 47,
 7: 48,
 8: 49,
 9: 41,
 10: 42,
 11: 43,
 12: 44,
 13: 45,
 14: 46,
 15: 47,
 16: 48,
 17: 49,
 18: 41,
 19: 42,
 20: 43,
 21: 44,
 22: 45,
 23: 46,
 24: 47,
 25: 48,
 26: 49,
 27: 42,
 28: 43,
 29: 44,
 30: 45,
 31: 46,
 32: 47,
 33: 48,
 34: 49,
 35: 44,
 36: 45,
 37: 46,
 38: 47,
 39: 48,
 40: 49,
 41: 47,
 42: 48,
 43: 49,
 44: 47,
 45: 48,
 46: 49,
 47: 49,
 48: 49,
 49: -1}

In [29]:
sample_num=50
keys = list(self_prob.keys())
random_index_list = np.random.randint(0, len(keys), sample_num)#从0--len(keys)-1 这么多个整数随机采样sample_num个，可能会重复
random_prob_list = np.random.random(sample_num)#sample_num个0-1的概率值
final_random_list = []

for idx, prob in zip(random_index_list, random_prob_list):
    if self_prob[keys[idx]] > prob:#self.prob越大越可能触发该条件
        final_random_list.append(keys[idx])
    else:
        final_random_list.append(self_alias[keys[idx]])#keys[idx]为小频率id时得对应的大频率id,keys[idx]为大频率id时-1


In [30]:
final_random_list

[46,
 34,
 49,
 44,
 46,
 48,
 42,
 45,
 48,
 48,
 46,
 48,
 12,
 42,
 47,
 17,
 47,
 38,
 1,
 44,
 48,
 26,
 47,
 48,
 47,
 27,
 44,
 16,
 14,
 47,
 2,
 8,
 48,
 47,
 43,
 42,
 41,
 43,
 6,
 47,
 44,
 43,
 42,
 28,
 47,
 49,
 48,
 44,
 47,
 47]

In [31]:
from collections import Counter
dict(Counter(final_random_list))

{46: 3,
 34: 1,
 49: 2,
 44: 5,
 48: 8,
 42: 4,
 45: 1,
 12: 1,
 47: 10,
 17: 1,
 38: 1,
 1: 1,
 26: 1,
 27: 1,
 16: 1,
 14: 1,
 2: 1,
 8: 1,
 43: 3,
 41: 1,
 6: 1,
 28: 1}

In [32]:
total_num=3
value_ids=[1,3,2]
used=[2]
np.arange(total_num)[np.isin(value_ids, used)]

array([2])

In [33]:
np.tile([1,2,3], 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [34]:
np.random.randint(1, 1000, 5)

array([631,  91, 428, 535, 424])